// <auto-generated />
using System;
using MagicVilla_villa_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_villa_API.Migrations
{
    [DbContext(typeof(ApplicationsDBContext))]
    partial class ApplicationsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_villa_API.Models.Villa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("detalis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgurl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.Property<double>("sqft")
                        .HasColumnType("float");

                    b.Property<DateTime>("updateddate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("villas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2023, 11, 30, 13, 30, 48, 43, DateTimeKind.Local).AddTicks(2046),
                            detalis = "Pool View Coool palce",
                            imgurl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fluxury-villa&psig=AOvVaw3-aHod71srN4UaKelBLHRF&ust=1701417603723000&source=images&cd=vfe&ved=0CBIQjRxqFwoTCMiL3tGg64IDFQAAAAAdAAAAABAE",
                            name = "Pool view",
                            rate = 100000.0,
                            sqft = 1300.0,
                            updateddate = new DateTime(2023, 11, 30, 13, 30, 48, 43, DateTimeKind.Local).AddTicks(2061)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
